export const SENDING_REQUEST = 'SENDING_REQUEST';

export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const EDIT_ITEM_IN_STORE = 'EDIT_ITEM_IN_STORE';
export const REQUEST_ITEM = 'REQUEST_ITEM';
export const REQUEST_PUT_DATA = 'REQUEST_PUT_DATA';

export const REQUEST_DELETE = 'REQUEST_DELETE';
export const DELETE_FOM_STORE = 'DELETE_FOM_STORE';
